# Generated by Django 5.2.3 on 2026-06-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelstation",
            name="is_geocoded",
            field=models.BooleanField(default=False),
        ),
    ]
